### ISSUE TITLE
Cross-Origin request blocked when accessing the builder compute API on upload

### ISSUE THREAD

**Issue by Ahsan2** [arduino/arduino-create-agent-js-client#147]
Facing CORS issue when making request to https://builder.arduino.cc/v3/boards/arduino:samd:mkr1000/compute when I try to upload sketch in the provided demo example.

Is there any additional configuration that I am missing?

**Comment by smellai** [comment]
I'm sorry that API is accessible only from Arduino domains

**Comment by Ahsan2** [comment]
I see
Thanks anyways
