### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by hpssjellis** [arduino/arduino-create-agent-js-client#253]
From both a windows and ubuntu computer I get the same error.

Form chrome console:

Access to fetch at 'http://127.0.0.1:8991/info' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
git clone https://github.com/arduino/arduino-create-agent-js-client

cd arduino-create-agent-js-client

sudo npm install

sudo npm run dev
```

Then put my chrome browser to http://localhost:8000/

My uno board is recognised by the online Arduino cloud.

If I was to add "no-cors" any suggestions as to where in the code? Or is there something I did wrong.

**Comment by smellai** [comment]
Hi @hpssjellis , did you have localhost:8000 in your agent config.ini?
https://github.com/arduino/arduino-create-agent/blob/devel/config.ini#L7

**Comment by hpssjellis** [comment]
Thanks @smellai, that will be the issue.  I noticed you have example locations for mac and linux 

```
On macOs ~/Applications/ArduinoCreateAgent-1.1/ArduinoCreateAgent.app/Contents/MacOS/config.ini
On Linux ~/ArduinoCreateAgent-1.1/config.ini
```

So I will try that location on my ubuntu machine, but any suggestions for where the config.ini is on windows. My basic search is showing my downloads of your repository but not the installed locations.

**Comment by smellai** [comment]
Can you look into `C:\Users\[your name]\AppData\Roaming\ArduinoCreateAgent-1.1`

**Comment by hpssjellis** [comment]
Great @smellai that was where it was. Strangely a hidden folder but entering \Users\[your name]\AppData found it. 

Have to go to work so will report later.

**Comment by hpssjellis** [comment]
Great, that works for a windows local server. The app can read the data from the Arduino-create-agent. Thanks for the help @smellai .

The bigger question is that I still have the CORS issues for when I try a cloud solution, I use https://gitpod.io perhaps allowing the cloud localhost equivalent is the solution so I will try that out.
